ci: fix build error while windows(rel) job
Run rcmdcheck::rcmdcheck(
  rcmdcheck::rcmdcheck(
    Sys.getenv("PKG_TARBALL"),
    args = c("--no-manual", "--as-cran"),
    build_args = character(),
    error_on = "warning",
    check_dir = "check"
  )
  shell: C:\R\bin\Rscript.EXE {0}
  env:
    GITHUB_PAT: ***
    R_KEEP_PKG_SOURCE: yes
    _R_CHECK_CRAN_INCOMING_REMOTE_: false
    _R_CHECK_FORCE_SUGGESTS_: false
    HANNLP_USER_DATA_DIR: D:\a\_temp/hannlp-user-data
    _R_INSTALL_TIME_PATCHES_: no
    R_LIBS_USER: D:\a\_temp\Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
    RSPM: https://packagemanager.posit.co/cran/latest
    RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.posit.co/cran/latest
    R_LIB_FOR_PAK: C:/R/site-library
    PKG_TARBALL: /d/a/hannlp/hannlp/HanNLP_0.1.0.tar.gz
Error in if (file.info(path)$isdir) { :
  missing value where TRUE/FALSE needed
Calls: <Anonymous>
Execution halted
Error: Process completed with exit code 1.